server:
  port: 8082
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      routes:
        - id: cart
          uri: lb://cart
          predicates:
            - Path=/cart/**
          filters:
            - StripPrefix=1
            - PrefixPath=/
            - JwtAuth=
        - id: user
          uri: lb://user
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
            - PrefixPath=/
            - JwtAuth=
        - id: order
          uri: lb://order
          predicates:
            - Path=/order/**
          filters:
            - StripPrefix=1
            - PrefixPath=/
            - JwtAuth=
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
